### ISSUE TITLE
xdebug.client_host = host.docker.internal make cli xdebug(drush) doesn't work on linux

### ISSUE THREAD

**Issue by lawxen** [INsReady/docker-drupal-dev#5]
https://github.com/INsReady/docker-drupal-dev/blob/5e6167b21720c5f04b6d2f93b286f8fdc54c46e5/9/Dockerfile#L24  
# Problem:  
Xdebug for CLI didn't work on linux
# Some findings
After many test, I found just the config  **_xdebug.client_host = 172.17.0.1_** works for drush when using linux (PS: add  PHP_IDE_CONFIG: serverName=*** to docker)   

# This is my test details:  
# Environment: 
Soft: Ubuntu 20.04 + phpstorm 2021.3  
part of docker-compose.yml:
```
  drupal:
    image: lawxen/drupal:d9-php80-dev
    environment:
      PHP_IDE_CONFIG: serverName=default
```
(PS: 
1. when PHP_IDE_CONFIG be added, the xdebug.discover_client_host won't work, you should add server config manually for phpstorm
2. Run `vendor/bin/drush ** `, not `drush **` 
)
# Result:  
| xdebug.client_host | web xdebug | CLI xdebug |
| host.docker.internal | work | didn't work |
| 172.0.0.1 | work | didn't work |
| 172.17.0.1 | work | work |
